[workspace]
members = ["bins/struct-sql-cli", "struct-sql", "struct-sql-macros"]
resolver = "2"

[workspace.package]
edition = "2024"

[workspace.dependencies]
log = { version = "0.4",}
proc-macro2 = { version = "1" }
quote = { version = "1" }
syn = { version = "2.0", features = ["parsing", "full"] }
postgres-types = "0.2"
tokio-postgres = { version = "0.7", default-features = false }
struct-sql-derive = { version = "0.1.0", path = "./struct-sql-macros" }
