[package]
name = "struct-sql"
version = "0.1.0"
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
struct-sql-derive = { workspace = true }
postgres-types = { workspace = true }
tokio-postgres = { workspace = true }
log = { workspace = true }


[dev-dependencies]
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true, features = [
    "parsing",
    "printing",
    "full",
    "extra-traits",
] }
